### ISSUE TITLE
Regarding channel combination with Siemens twix data

### ISSUE THREAD

**Issue by minton1234** [openmrslab/suspect#123]
What is the difference between simple_mean and rda file data ?
<img width="821" alt="スクリーンショット 2019-05-30 22 09 32" src="https://user-images.githubusercontent.com/51200233/58635015-ba0eb500-8327-11e9-856e-dbef9ffb4360.png">

I  could not improve SNR using twix data compared with rda data at lcmodel analysis.

**Comment by bennyrowland** [comment]
Hi @minton1234, the way that the data for the .RDA file is calculated is not documented by Siemens, so it is impossible to be exactly sure how everything is done. However, it is my understanding that they use "Brown's method" of using the phase and magnitude of the first point to calculate the weighting factors. This is analogous to the `phase_correct_and_scale()` method here, rather than the simpler `phase_correct()` method used to calculate `simple_mean`. Therefore the .RDA file should be more similar to the `channel_combined_data` value.

In fact channel combination in this way is generally very good, as long as the available signal for that first point is good. Unfortunately in some cases the first points of the FID can be corrupted or suppressed, and in other cases the SNR is not good enough (for example in very deep voxels) to get a good estimate from the first point. This is why we recommend using the WSVD method which gives the same result as Brown's method in the ideal case, but is more robust when the data quality is lower. Basically, if you have good raw data, the .RDA processing should also result in good quality spectra and you don't gain anything by moving to twix, but if there are issues, such as poor channel combination or frequency drifts between averages, you will see substantial improvements in SNR.

However, related to that, be careful because the reported SNR in LCModel is unfortunately not a good measure of the true SNR of the signal. This is because it compares the signal height to the residual signal in the spectral analysis region. This means that any peaks which are not fitted (or partially fitted) are considered as noise. This means that increasing the height of all peaks relative to the actual noise, as with the blue line using `phase_correct_and_scale()` above, is interpreted by LCModel as an increase in both noise and signal, so the overall SNR doesn't change, even though the peaks are much higher against the noise outside the spectral analysis region where there is only noise.

I hope that helps, feel free to ask any other questions if things aren't clear.

**Comment by minton1234** [comment]
Hi @bennyrowland 
Thank you for giving me a lot of advice. 
The problem I had were resolved thanks to for your help.
I am going to try WSVD method using twix data.

I did not know the true SNR in LCModel. 
So, other methods to measure SNR of spectra data will be needed.

Thank you.
