### ISSUE TITLE
LCModel IO - "VOLUME = NaN"

### ISSUE THREAD

**Issue by bkossows** [openmrslab/suspect#145]
For 20% Siemens TWIX data I was unable to run LCModel analysis with an error 1 FATAL ZEROVX 4. In CONTROL file there was "VOLUME = NaN" instead of a some numerical value.
B.

**Comment by bennyrowland** [comment]
Hi @bkossows, this will be a problem with loading the transform data so Suspect doesn't know the voxel dimensions so when it exports it leaves this NaN for volume. Or possibly with some kind of corruption of the transform. What happens if you just run `print(data.transform)`? Can you share any of this problem data for me to have a look at?

**Comment by bkossows** [comment]
I will send You the file by an email.

print(data.transform)

[[      nan       nan       nan -0.586961]
 [      nan       nan       nan 56.045076]
 [      nan       nan       nan 11.650538]
 [ 0.        0.        0.        1.      ]]
