### ISSUE TITLE
Compatibility issues in the latest version of Suspecs (v0.4.4)

### ISSUE THREAD

**Issue by handehio** [openmrslab/suspect#167]
Hello!

I recently updated my Suspect from 0.3.8 to 0.4.4. However, in the new version there are a lot of errors in data and function compatibility between suspect and other Python toolboxes utilized. I'm debugging and editing my way through my pipeline :) Are there any plans to address this or any maintenance plans?

Thanks! 

Best,
Hande

**Comment by bennyrowland** [comment]
@handehio sorry to hear that you are having these issues. I don't have a lot of time any more to maintain Suspect so there won't be any feature releases unless contributed by other people. But if you can give me some specifics of the issues that you have been seeing then I will try and figure out if we can put together a compatible release.

**Comment by darrencl** [comment]
@handehio Is this related to NumPy version, by any chance?

If that is the case, I think it is related to #162. I also found compatibility issue on fresh install on my colleague's Mac due to NumPy versions. Suspect currently pins the lmfit to an older version, which also restricts suspect to use an old version of NumPy since lmfit depends on NumPy.

**Comment by handehio** [comment]
@darrencl My code first broke because of the numpy version, specifically float -> float64. I fixed this one by hand. Then it broke at lmfit at np.asfarray() and I couldn't fix that. I'll take look into my numpy version as well to see if that helps maybe. Thanks for the heads up!
